project sistem_bimbingan_akademik {
    database_type:"PostgreSQL"
}

table pengguna{
id integer [pk, increment]
nama varchar
email varchar
password varchar
peran varchar // admin || dosen || mahasiswa
reset_token varchar
dibuat_pada timestamp
diperbarui_pada timestamp
}

table mahasiswa{
id integer [pk, increment]
pengguna_id integer [ref: > pengguna.id]
nim varchar
fakultas varchar
program_studi varchar
angkatan integer
kelas_bimbingan_id integer [ref: > kelas_bimbingan.id]
}

table dosen{
id integer [pk, increment]
pengguna_id integer [ref: > pengguna.id]
nidn varchar
fakultas varchar
}

table kelas_bimbingan{
id integer [pk, increment]
nama_kelas varchar
fakultas varchar
program_studi varchar
angkatan integer
dosen_id integer [ref: > dosen.id]
komting_id integer [ref: > mahasiswa.id]
}

table bimbingan_kelas{
id integer [pk, increment]
kelas_bimbingan_id integer [ref: > kelas_bimbingan.id]
tanggal date
jam time
status varchar // menunggu || diterima || ditolak || selesai
catatan text
}

table notifikasi{
id integer [pk, increment]
pengguna_id integer [ref: > pengguna.id]
judul varchar
pesan text
status_baca varchar //sudahbaca || belum dibaca
dibuat_pada timestamp
}